using PSyringe.Common.Language.Elements;

namespace PSyringe.Common.Language.Compiler;

/// <summary>
///   Updates a Script Definition generated by the PSyringe Parser.
///   Implementations can be provided to the script compiler as to update
///   the script definition before it is compiled to a PSyringe Script.
/// </summary>
public interface IScriptTransformer {
  public void Transform(ref IScriptDefinition script);
}